Update build_spec_full_flow.yml

diff --git a/build_spec_full_flow.yml b/build_spec_full_flow.yml
--- a/build_spec_full_flow.yml
+++ b/build_spec_full_flow.yml
@@ -3,39 +3,13 @@ component: build
 timeoutInSeconds: 6000
 runAs: root
 shell: bash
+failImmediatelyOnError: true
 steps:
   - type: Command
-    timeoutInSeconds: 600
-    name: "Building HelloWorld"
+    name: "Test fail"
     command: |
-      cd src/main/java/org/example/
-      javac HelloWorld.java
+      exit 1
     onFailure:
       - type: Command
         command: |
-          echo "Building HelloWorld failed :("
-        timeoutInSeconds: 400
-        runAs: root
-  - type: Command
-    timeoutInSeconds: 600
-    name: "Create Docker Artifact"
-    command: |
-      docker build -t hello-test:1.0 .
-    onFailure:
-      - type: Command
-        command: |
-          echo "Docker image could not be created :("
-        timeoutInSeconds: 400
-        runAs: root
-  - type: Command
-    timeoutInSeconds: 600
-    name: "Creating Generic Artifact"
-    command: |
-      echo "Hello World" > abc.txt
-outputArtifacts:
-  - name: hello_dev_image
-    type: DOCKER_IMAGE
-    location: hello-test:1.0
-  - name: ABC
-    type: BINARY
-    location: abc.txt
+          echo "RUNNING ON FAILURE"
