Update build_spec_full_flow.yml

diff --git a/build_spec_full_flow.yml b/build_spec_full_flow.yml
--- a/build_spec_full_flow.yml
+++ b/build_spec_full_flow.yml
@@ -8,4 +8,9 @@ steps:
   - type: Command
     name: "Test fail"
     command: |
-      docker ps
+      echo SHABBA $OCI_PRIMARY_SOURCE_URL
+      exit 1
+    onFailure:
+      - type: Command
+        command: |
+          echo "RUNNING ON FAILURE"
